# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  # lane :testflightStaging do
  #   sh "fastlane incrementBuildNumber"
  #   sh "fastlane commitVersionChanged"
  #   sh "fastlane buildApp"
  #   sh "fastlane upload_to_testflight"
  # end

  lane :buildApp do 
    build_app(workspace: "HelloWidget.xcodeproj", scheme: "HelloWidget")
    enable_automatic_code_signing(path: "HelloWidget.xcodeproj")
  end
end
